# Generated by Django 3.2.12 on 2022-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=50)),
                ('questionno', models.CharField(max_length=3)),
                ('question', models.CharField(max_length=250)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('solution', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='studentface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('studentid', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='examdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('examid', models.CharField(max_length=50)),
                ('exampassword', models.CharField(max_length=50)),
                ('examname', models.CharField(max_length=50)),
                ('noq', models.CharField(max_length=3)),
            ],
            options={
                'unique_together': {('email', 'examid')},
            },
        ),
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('organisationcode', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('email', 'organisationcode')},
            },
        ),
    ]
