# Generated by Django 3.2.12 on 2022-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='examattend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=30)),
                ('examid', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=30)),
            ],
        ),
    ]
